### ISSUE TITLE
`dispatch is not defined`

### ISSUE THREAD

**Issue by felixakiragreen** [alinz/example-react-native-redux#1]
When I run this code exactly, I get the red screen and `dispatch is not defined`. Any idea why?

**Comment by alinz** [comment]
Thanks @dubert give me couple of min and I get back to you!

**Comment by felixakiragreen** [comment]
Hey! It's a bug with babel: https://github.com/babel/babel/issues/2086

Sorry for the bother, I just found out.

**Comment by alinz** [comment]
That's good. But you shouldn't get this error since you are using a custom version of react-native, plus, packager is has its own babel instance. so, I need a little bit more info from you. Do you install Babel globally? Did you change anything in project?

UPDATE: I got into the same issue. Thanks for point it into babel issue
